alias proj='cd ~/Projects/'
alias touchoff='synclient TouchpadOff=1'
alias touchon='synclient TouchpadOff=0'
alias agi='sudo apt-fast install'
alias checksyn='synclient | grep TouchpadOff'
alias zlogin='/bin/zsh --login'
alias sshetsu='ssh zjeb40@einstein.etsu.edu'
alias hf-update='source hub-flow-update.sh'
alias apt-get='apt-fast'
